on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - run: npm ci

    - run: npm run lint

    - run: npm run build

    - name: Verify prerendered HTML
      run: npm run verify:prerender
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_url }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: dist/
        server-dir: www/ferd/
